-- MySQL Script generated by MySQL Workbench
-- 2017. okt.  4., szerda, 20:01:28 CEST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema ganesh
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema ganesh
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ganesh` DEFAULT CHARACTER SET utf8 ;
USE `ganesh` ;

-- -----------------------------------------------------
-- Table `ganesh`.`places`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ganesh`.`places` (
  `id` SMALLINT UNSIGNED NOT NULL,
  `name` VARCHAR(45) NULL,
  `address` VARCHAR(255) NULL,
  `lat` FLOAT(10,6) NULL,
  `lng` FLOAT(10,6) NULL,
  UNIQUE INDEX `name_UNIQUE` (`name` ASC),
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `ganesh`.`festivals`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ganesh`.`festivals` (
  `id` SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `place_id` SMALLINT UNSIGNED NOT NULL,
  `name` VARCHAR(255) NULL,
  `start` DATETIME NULL,
  `end` DATETIME NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_festivals_places_idx` (`place_id` ASC),
  CONSTRAINT `fk_festivals_places`
    FOREIGN KEY (`place_id`)
    REFERENCES `ganesh`.`places` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `ganesh`.`managers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ganesh`.`managers` (
  `id` TINYINT UNSIGNED NOT NULL,
  `name` VARCHAR(45) NULL,
  `phone` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `ganesh`.`departments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ganesh`.`departments` (
  `id` TINYINT UNSIGNED NOT NULL,
  `manager_id` TINYINT UNSIGNED NOT NULL,
  `place_id` SMALLINT UNSIGNED NOT NULL,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_departments_managers1_idx` (`manager_id` ASC),
  INDEX `fk_departments_places1_idx` (`place_id` ASC),
  CONSTRAINT `fk_departments_managers1`
    FOREIGN KEY (`manager_id`)
    REFERENCES `ganesh`.`managers` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_departments_places1`
    FOREIGN KEY (`place_id`)
    REFERENCES `ganesh`.`places` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `ganesh`.`activities`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ganesh`.`activities` (
  `id` MEDIUMINT UNSIGNED NOT NULL,
  `festival_id` SMALLINT UNSIGNED NOT NULL,
  `department_id` TINYINT UNSIGNED NOT NULL,
  `name` VARCHAR(45) NULL,
  `start` DATETIME NULL,
  `end` DATETIME NULL,
  `manpower` SMALLINT UNSIGNED NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_activities_departments1_idx` (`department_id` ASC),
  INDEX `fk_activities_festivals1_idx` (`festival_id` ASC),
  CONSTRAINT `fk_activities_departments1`
    FOREIGN KEY (`department_id`)
    REFERENCES `ganesh`.`departments` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_activities_festivals1`
    FOREIGN KEY (`festival_id`)
    REFERENCES `ganesh`.`festivals` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `ganesh`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ganesh`.`users` (
  `id` SMALLINT UNSIGNED NOT NULL,
  `name` VARCHAR(45) NULL,
  `phone` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `female` TINYINT(1) NULL DEFAULT 1,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_phone_email` (`name` ASC, `phone` ASC, `email` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `ganesh`.`activities_users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ganesh`.`activities_users` (
  `user_id` SMALLINT UNSIGNED NOT NULL,
  `activitie_id` MEDIUMINT UNSIGNED NOT NULL,
  `start` DATETIME NULL,
  `end` DATETIME NULL,
  `fulltime` TINYINT(1) NULL DEFAULT 0,
  PRIMARY KEY (`user_id`, `activitie_id`),
  INDEX `fk_people_has_activities_activities1_idx` (`activitie_id` ASC),
  INDEX `fk_people_has_activities_people1_idx` (`user_id` ASC),
  CONSTRAINT `fk_people_has_activities_people1`
    FOREIGN KEY (`user_id`)
    REFERENCES `ganesh`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_people_has_activities_activities1`
    FOREIGN KEY (`activitie_id`)
    REFERENCES `ganesh`.`activities` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
